### ISSUE TITLE
Do not add NavigationControl by default

### ISSUE THREAD

**Issue by crazycapivara** [eodaGmbH/py-maplibregl#31]
Add a parameter `navigation_control` to `MapOptions`:

```python
class MapOption(BaseModel):
   # ...
   navigation_control: bool = True
```

**Comment by giswqs** [comment]
Any updates on this feature? It would be great to be able to customize the position of the NavigationControl. Since the default map adds the NavigationControl by default, adding a new one ends up with duplicate controls. 

![image](https://github.com/eodaGmbH/py-maplibregl/assets/5016453/e5b5439a-6682-4385-96be-763449d316dc)
